### PR TITLE
mixin -> @apply. Also fixes #7

### LINKED ISSUE #7: Docs: copied docs from other elements
https://github.com/PolymerElements/iron-component-page/blob/master/iron-component-page.html#L15-L38

references `iron-doc-element` and `iron-doc-page`.  This element needs its own docs.

### PR DESCRIPTION
**Pull request by ebidel**
R: @cdata, all

### CODE REVIEW

**Comment by ebidel** [comment]
Ping

**Comment by cdata** [comment]
Sorry, got lost in the shuffle. Checking it out.

**Comment by cdata** [comment]
LGTM :+1:

**Comment by ebidel** [comment]
:+1: thx

**Pull request merged**
