### PR TITLE
Make use of hydrolysis API to load transitive behaviors but only disp…

### PR DESCRIPTION
**Pull request by garlicnation**
…lay the local folder.

### CODE REVIEW

**Comment by rictic** [comment]
:+1:

**Comment by blasten** [comment]
@garlicnation is this still relevant? If so, would you mind rebasing it?

**Comment by cdata** [comment]
This PR is looking good, but it needs a rebase before it can be merged. I'm going to close it for now, but please re-open it after you have performed a rebase!

**Comment by vguillou** [comment]
👍  This would be very welcome @garlicnation, do you plan on submitting this again ?

**Comment by garlicnation** [comment]
Reopened in https://github.com/PolymerElements/iron-component-page/pull/86

**Pull request closed without merging**
