### PR TITLE
Add support for multiple demos selectable via paper-dropdown-menu

### PR DESCRIPTION
**Pull request by MeTaNoV**
This PR fixes the following issue:
- #67 
- #20

### CODE REVIEW

**Comment by MeTaNoV** [comment]
@David-Mulder for you to test! @cdata PTAL! :)

**Comment by MeTaNoV** [comment]
A live working example can be found here: https://metanov.github.io/iron-swipeable-pages/components/iron-swipeable-pages/

**Comment by justinfagnani** [comment]
I think that for the docs + 1 demo case this is a UX regression. It's not immediately apparent anymore that there even are demos, since they're hidden in the dropdown.

Without the benefit of a UX designer weighing in, I wonder if we could keep the docs button and have a dropdown only for demos. Even better, IMO, would be keeping a single demo link which then showed the default demo with a menu to choose from additional demos if available.

**Comment by justinfagnani** [comment]
Also, I'm in the middle of replacing the element/behavior dropdown with a drawer panel. Maybe the demos could be listed there...

**Comment by MeTaNoV** [comment]
This was a first draft just to test the behavior. I am no UX designer, so yes, It could be presented better. I can test your last option or let you do it! :)

**Comment by MeTaNoV** [comment]
@justinfagnani any news?

**Comment by aomarks** [comment]
Closing this PR as the 3.0 RC shows multiple demos in the new nav panel.

demos

**Pull request closed without merging**
