### PR TITLE
window.console -> Polymer.Base

### PR DESCRIPTION
**Pull request by valdrinkoshi**
Merge after https://github.com/Polymer/polymer/issues/3574 gets fixed.

### CODE REVIEW

**Comment by abdonrd** [comment]
@valdrinkoshi you link an issue, not a PR. :)

**Comment by valdrinkoshi** [comment]
@abdonrd I linked the issue that needs to be fixed before this PR can be merged. No PR is available for that issue yet.

**Comment by abdonrd** [comment]
@valdrinkoshi ah, okey! Thanks! :)

**Comment by notwaldorf** [comment]
LGTM

**Comment by justinfagnani** [comment]
Won't we need an associated version constraint bump for the polymer dep?

**Comment by valdrinkoshi** [comment]
You're right @justinfagnani, I'll wait for it to be published & will update all these PRs

**Comment by justinfagnani** [comment]
btw, what is the advantage of using Polymer's logging over console?

**Comment by valdrinkoshi** [comment]
@justinfagnani, updated the version constraint, PTAL

**Comment by aomarks** [comment]
Closing this PR as development has moved to the 3.0 Analyzer version (on master and RC).

Still curious to hear why we might want to use Polymer's logging over console?

**Comment by aomarks** [comment]
Why do we want to do that?

**Comment by valdrinkoshi** [comment]
Some Polymer users relied on these protected methods to disable warnings or logs coming from certain components. `Polymer.Base` was already exposing these, but not many PolymerElements were actually using those.

**Pull request closed without merging**
